### ISSUE TITLE
Missing tensorflow repo

### ISSUE THREAD

**Issue by Tao-Hu-L** [trigeorgis/mdm#10]
when I run "git clone git@github.com:trigeorgis/tensorflow.git", but with error output:
"Cloning into 'tensorflow'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists."
 Does the tenforflow missing? Thank you!

**Comment by cassidylaidlaw** [comment]
Try running `git clone https://github.com/trigeorgis/tensorflow.git`, it worked for me!
