### ISSUE TITLE
AttributeError: 'PointCloud' object has no attribute '_group_label'

### ISSUE THREAD

**Issue by gmh14** [trigeorgis/mdm#14]
Traceback (most recent call last):
  File "mdm_train.py", line 257, in <module>
    train()
  File "mdm_train.py", line 82, in train
    data_provider.load_images(train_dirs)
  File "/home/hliu/Desktop/code/mdm/data_provider.py", line 150, in load_images
    group = group or im.landmarks[group]._group_label

Hi, I get a problem on menpo. My menpo version is 0.8.1. 
I change the line 150 to " group = group or im.landmarks.keys()[0] ", it works.
But the trained result is bad. I wonder if this is the reason.

**Comment by ganlinzhang** [comment]
I have the same question,
AttributeError: 'PointCloud' object has no attribute '_group_label'
so,how did you solve the problem?
Thank you.
