### ISSUE TITLE
Questions about the calculation of AUC

### ISSUE THREAD

**Issue by D-X-Y** [trigeorgis/mdm#15]
Hi Trigeorgis,

Thanks for your code.
I have few questions about your AUC.
In your code, https://github.com/trigeorgis/mdm/blob/fc8d011e0d7a34320aa0f971b60c9c0fa696e054/mdm_eval.py#L130
you calculate the auc via `(errors < .08).mean()`

I think it should be the accuracy of the 0.08 threshold rather than AUC?
Would you mind to let me how to calculate the auc@0.08? Thanks a lot.

**Comment by trigeorgis** [comment]
Yes, you are correct. That was bad naming on my part. You can use this function to calculate the threshold AUC.

https://github.com/menpo/menpofit/blob/master/menpofit/error/stats.py#L45
