### ISSUE TITLE
Update extract patches function in Tensorflow v0.10.0

### ISSUE THREAD

**Issue by ShownX** [trigeorgis/mdm#3]
Hey, Georgis,

I have question about moving extracting patches function in v0.10.0. But now it happen with problem that without shape function.

Do you know how to define the shape function for the extracting patches?

**Comment by zbzoujianfa** [comment]
in the latest version of tensor flow, the interface has been changed to tf.extract_image_patches.

**Comment by trigeorgis** [comment]
Hi ShownX,

I will soon put up a newer version of the code which doesn't depend on a custom build of TF.

**Comment by taopanpan** [comment]
how Update extract patches function in Tensorflow v1.0.0 ， can you provide some advices? THX

**Comment by ShownX** [comment]
@taopanpan You can use slice operation and then ```tf.stack```

**Comment by MoExplorer** [comment]
I have a question

**Comment by MoExplorer** [comment]
@ShownX  Hello, I could not compile the extract_patches.cc in the tensorflow r0.11. You said **slice operation and tf.stack** could work. Could please give me more details about it? I have spent two days on this problem, but I have not solved it...Thanks!

**Comment by trigeorgis** [comment]
There is a version of extract patches function using slices in the refactored branch. You can try that out!
