### ISSUE TITLE
Mapping of (face detection) bounding box points, from dlib output to final points used/stored in bbs folder.

### ISSUE THREAD

**Issue by gp1313** [trigeorgis/mdm#8]
@trigeorgis Can you provide the mapping performed on dlib output (for frontal face detection) to get bounding box used for facial key point prediction.

**Comment by superphil0** [comment]
This model, as far as I know was trained on rectangular hull of ground truth face points. If you want to use dlib bboxes make sure they are tight and retain the model ( works best I have tried many variants)
