### ISSUE TITLE
Environment establishment

### ISSUE THREAD

**Issue by Dingyuan-Zheng** [trigeorgis/mdm#9]
I'm a newbie in Tensorflow. Currently, I'm trying to run the demo (Demo.ipynb) given in the source code. But I can't install Tensorflow (using the method: 'install from source' given in the Tensorflow official website) inside the Conda environment. Specifically,  after I git clone from the repository (https://github.com/trigeorgis/tensorflow), I can't pass the configure operation (./configure),   could you give me a detailed manual for the environment configuration?
I've installed menpo package under Conda environment, what should I do next? How can I install Tensforflow from your repository into Conda environment, then I can import both Tensorflow and menpo libraries at the same time.

**Comment by HuitingLiu** [comment]
Same here. Following the instructions: https://www.tensorflow.org/install/install_sources

There are two errors:
bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
ERROR: tensorflow/tensorflow/tensorflow.bzl:476:19: name 'DATA_CFG' is not defined.
ERROR: error loading package '': Extension 'tensorflow/tensorflow.bzl' has errors.

**Comment by superphil0** [comment]
Had the same problem make sure you use the bazel version which was used at the time to 0.8 was released. Same for protobuf versions and all other dependencies

**Comment by qiexing** [comment]
@HuitingLiu I have the exactly same problem as you, did you solve this problem?

**Comment by euklid** [comment]
same here. Probably would be best if the changes applied to the older tensorflow version could be ported to a newer version of tensorflow. However, I'm not familiar with tensorflow at all, but wanted to try this code...

**Comment by zhm1995** [comment]
@HuitingLiu Hello？ I have the same problem with you. Have you solved this problem?

**Comment by trigeorgis** [comment]
You can try the implementation provided at the experimental branch, but unfortunately it doesn't come with a pretrained model.

**Comment by devvikas** [comment]
@trigeorgis You can try the implementation provided at the experimental branch, but unfortunately it doesn't come with a pretrained model.

Which branch are you talking about here ?
